export const env = {
  API_URL: process.env.EXPO_PUBLIC_API_URL,
  WEB_GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_WEB_GOOGLE_CLIENT_ID,
  IOS_GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_IOS_GOOGLE_CLIENT_ID,
};
